---
title: "OHI `r format(Sys.Date(), '%Y')` - Livelilihoods (liv): Labor Force Data Preparation"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: show
    toc: true
    toc_depth: 1
    toc_float: yes
    number_sections: true
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '../../../workflow/templates/ohi_hdr.html'
pdf_document:
  toc: true
editor_options: 
  chunk_output_type: console
  markdown: 
    wrap: 72
---

# Livelihoods: Proportion of Tourism Jobs per Country/Region per Year

## Overview

* **Data:** Labor Force & Employment Data

  * Labor Force data from World Bank, last updated 7/1/25 (downloaded August 7, 2025).

      - https://data.worldbank.org/indicator/SL.TLF.TOTL.IN
      - Click the csv button on the bottom/middle right under the download heading.


### Setup

```{r}
knitr::opts_chunk$set(eval = FALSE, warning = FALSE, message = FALSE)

# load packages
if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}
librarian::shelf(
  ohicore,
  here,
  janitor,
  terra,
  countrycode,
  readxl,
  RColorBrewer,
  foreach,
  tidyverse, 
  httr,
  plotly,
)


# source 
source(here("workflow", "R", "common.R"))

# ---- set year and file path info ----
current_year <- 2025 # Update this in the future!!
previous_year <- 2024

version_year <- paste0("v",current_year)
previous_vyear <- paste0("v", previous_year)

current_data_dir <- paste0("d", current_year)
previous_data_dir <- paste0("d", previous_year)

# ---- data directories ----

# Raw data directory (on Mazu)
raw_data_dir <- here::here(dir_M, "git-annex", "globalprep", "_raw_data")

# WorldBank raw data directory
current_wb_dir <- here(raw_data_dir, "WorldBank", current_data_dir)

# Livelihoods and Economies directory
current_le_dir <- here("globalprep", "le", version_year)
previous_le_dir <- here("globalprep", "le", previous_vyear)
```

Create country code --> iso3 function

```{r}
country_regex_to_iso3c <- function(country_string) {
  country_string %>%
    countrycode::countrycode(origin = "country.name", destination = "iso3c", origin_regex = TRUE)
}
```

### Read in Data

```{r}
# ===================== Read in Data ==============================
# Labor force data ----
labor_raw <- read_csv(here(current_wb_dir, "WorldBank_total_labor_force_1990-2024",
                                   "API_SL.TLF.TOTL.IN_DS2_en_csv_v2_38674.csv"),
                               skip = 4, # How many rows to skip before data starts,
                              # Manually open the file to confirm. changes year to year
                               na = "")

# OHI regions data ----
# read in OHI regions for joining
region_names <- read_csv("https://raw.githubusercontent.com/OHI-Science/ohi-global/draft/eez/spatial/regions_list.csv") 



# ==================== Tidy Data ===================================

# Labor force data -----------------------------------
labor_clean <- labor_raw %>% 
  # conver to lower_snake_case
  janitor::clean_names() %>% 
  # tidy data from wide to long (years are currently columns)
  pivot_longer(cols = 5:length(names(labor_raw)),
               names_to = "year", 
               values_to = "labor_force_total") %>% 
  # remove unnecessary columns
  select(-c(indicator_name, indicator_code)) %>% 
  # clean up year column (currently in the form of xYYYY)
  mutate(year = str_remove_all(year, pattern = "x")) %>% 
  # fix data types
  mutate(year = as.numeric(year),
         country_name = as.factor(country_name),
         labor_force_total = as.numeric(labor_force_total)) %>% 
  filter(year >= 2009) # starting 5 years back from first year of evaluation
  

# clean regions data --------------
region_clean <- region_names %>% 
  janitor::clean_names() %>% 
  # drop notes column
  select(-c(("notes")))


# ============== Run ohicore name_2_rgn ==================================
# check names
labor_rgn <- name_2_rgn(df_in = labor_clean, 
                       fld_name='country_name',
                      flds_unique = c("year"))

duplicates <- labor_rgn[duplicated(labor_rgn[, c("rgn_name", "year")]),]

unique(duplicates$country_name)
unique(duplicates$rgn_name)

# aggregating to address duplicates ----

# we don't need to do a weighted average since the values can just be added (end goal is total labor force)
# China: Hong Kong, Macao
# Northern Mariana Islands and Guam: Northern Mariana Islands, Guam 
# Puerto Rico and Virgin Islands of the United States: Puerto Rico, Virgin Islands (U.S.)


labor_rgn_agg <- labor_rgn %>%
  group_by(rgn_id, rgn_name, year) %>%
  dplyr::summarize(labor_force_total = sum(labor_force_total, na.rm=TRUE)
            )%>%
  ungroup() %>% 
  dplyr::mutate(year = as.numeric(year)) %>% 
  mutate(labor_force_total = case_when(
    labor_force_total == 0 ~ NA, # replace 0s with NAs, because there are no true 0s in our dataset -- NAs became 0s in the summarize step earlier
    .default = labor_force_total
  ))
 # mutate(eez_iso3 = country_regex_to_iso3c(rgn_name))

# because we aggregated, getting EEZs is more complicated... OHI has assigned certain EEZ ISO3 codes to these aggregated regions, so if you want EEZ ISO3 codes, you'll need to join with regions_clean read in earlier by rgn_name
# Caused by warning:
#! Some values were not matched unambiguously: Micronesia, Northern Mariana Islands and Guam, Northern #Saint-Martin, Puerto Rico and Virgin Islands of the United States


labor_export <- labor_rgn_agg %>% 
  mutate(rgn_id = as.character(rgn_id),
         unit = "Persons (1)",
         sector = "liv",
         data_source = "World Bank")

# save csv for use in other livelihood dataprep
write_csv(labor_export, here(current_le_dir, "int", "liv_labor_force.csv"))
```

# Data check

```{r}
# Read in data
new_le <- read_csv(here(current_le_dir, "int", "liv_labor_force.csv"))
old_le <- read_csv(here(previous_le_dir, "int", "liv_labor_force.csv"))

# Get max data years for plotting
current_data_year <- max(new_le$year)
current_data_year
previous_data_year <- max(old_le$year)
previous_data_year

colSums(is.na(new_le)) # 390
nrow(new_le) # 2656

colSums(is.na(old_le)) # 362
nrow(old_le) # 2490


# Combine data frames
comb_le <- new_le %>% 
  rename(new_labor_force = labor_force_total) %>% 
  left_join(old_le, by = join_by(rgn_id, year, rgn_name))


# Plot
comp_plot1 <- ggplot() + 
  geom_jitter(data = filter(comb_le, year == previous_data_year), aes(x = labor_force_total, y = new_labor_force, text = paste("Year:", year, "<br>Region:", rgn_name)), alpha = 0.7) +
  labs(x = paste("Previous Value", previous_data_year),
       y = paste("Current Value", previous_data_year),
       title = paste("Total Labor Population", previous_data_year, "Data", previous_year, "Assessment vs.", previous_data_year, "Data", current_year, "assessment")) +
  geom_abline(slope = 1, intercept = 0, col = "red", alpha = 0.7) +
  theme_bw();ggplotly(comp_plot1)
```


