---
title: "OHI `r format(Sys.Date(), '%Y')` - FIS LIV Quality Preparation"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: show
    toc: true
    toc_depth: 1
    toc_float: yes
    number_sections: true
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '../../../../workflow/templates/ohi_hdr.html'
  pdf_document:
    toc: true
editor_options: 
  chunk_output_type: console
---

# FIS Livelihoods: Quality of Tourism Jobs per Country/Region per Year

## Overview

**Data:**

-   ILOSTAT (downloaded August 27, 2025) -- for fis wage data

    ```         
    - <https://rshiny.ilo.org/dataexplorer46/?lang=en&id=EAR_4MTH_SEX_ECO_CUR_NB_A>
    - select Rev 3.1.B: Fishing, Sex: Total, all regions, all years
    - `ilostat_fishing_wages_2008-2020.csv`
    ```

-   OECD (downloaded August 27, 2025) -- for ppp adj

    ```         
    - <https://data-explorer.oecd.org/vis?lc=en&tm=ppp&pg=0&snb=111&vw=ov&df[ds]=dsDisseminateFinalDMZ&df[id]=DSD_NAMAIN10%40DF_TABLE4&df[ag]=OECD.SDD.NAD&df[vs]=1.0&dq=A.AUS%2BAUT%2BBEL%2BCAN%2BCHL%2BCOL%2BCRI%2BCZE%2BDNK%2BEST%2BFIN%2BFRA%2BDEU%2BGRC%2BHUN%2BISL%2BIRL%2BISR%2BITA%2BJPN%2BKOR%2BLVA%2BLTU%2BLUX%2BMEX%2BNLD%2BNZL%2BNOR%2BPOL%2BPRT%2BSVK%2BSVN%2BESP%2BSWE%2BCHE%2BTUR%2BGBR%2BUSA...PPP_B1GQ.......&pd=2009%2C2020&to[TIME_PERIOD]=false>
    - `OECD_2009-2023_fishing_ppp_wages.csv`
    ```

### Setup

```{r setup}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, eval=FALSE)

# load packages
if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}
librarian::shelf(
  here,
  ohicore,
  janitor,
  terra,
  readxl,
  RColorBrewer,
  foreach,
  doParallel, # for using multiple cores
  tidyverse, 
  httr,
  plotly,
  zoo, # for gapfilling
  pdftools
)


# source 
source(here("workflow/R/common.R"))

source(here('workflow/R/fao_fxn.R')) # function for cleaning old version of FAO data 

source(here('workflow/R/fao_online_portal_clean.R'))

# set year and file path info
current_year <- 2025 # Update this!!

version_year <- paste0("v",current_year)
data_dir_version_year <- paste0("d", current_year)
data_path <- here("globalprep", "liv", version_year)

# Raw data directory (on Mazu)
raw_data_dir <- here::here(dir_M, "git-annex", "globalprep", "_raw_data")

# world bank raw data directory
wb_dir <- here(raw_data_dir, "WorldBank", data_dir_version_year)

# ILO raw data directory
ilo_dir <- here(raw_data_dir, "ILOSTAT", data_dir_version_year)

# FAO raw data directory
fao_dir <- here(raw_data_dir, "FAO", data_dir_version_year)

# OECD raw data directory
oecd_dir <- here(raw_data_dir, "OECD", data_dir_version_year)

# FAO capture raw data directory
fao_capture_dir <- here(raw_data_dir, "FAO_capture", data_dir_version_year)

# Ex-vessel raw data directory
ex_vess_dir <- here(raw_data_dir, "ex-vessel-price-database-updated")

# OECD and FAO joint collection raw data directory
oecd_fao_dir <- here(raw_data_dir, "OECD_FAO_joint_collection", data_dir_version_year)

# output data dir for intermediate data products
int_dir <- here(data_path, "int")
```

### Read in Data

```{r}
#-------cf ILO wage data (2009 - 2021) -------
# this data has limited entries, so local currency will need to be ppp adjusted to increase the number of observations per geo area
fis_ilo_wage_raw <- read_csv(here(ilo_dir, "ilostat_fishing_wages_2008-2020.csv"), show_col_types = FALSE) %>%
  filter(sex.label == "Total")

fis_wage_ppp_raw <- read_csv(here(oecd_dir, "OECD_2009-2023_fishing_ppp_wages.csv"), show_col_types = FALSE)
```

# Livelihood: Quality of Jobs -- fis

-   note: this data came from many sources and was compiled by ILO. PPP
    GDP adjustments come from OECD

Cleaning and wrangling data

```{r}
# separating into the different currencies
fis_ilo_wage <- fis_ilo_wage_raw %>% 
  janitor::clean_names() %>% 
  rename(currency = classif2_label, 
         year = time) %>% 
  select(ref_area_label, year, currency,obs_value, note_indicator_label, source_label)

length(unique(fis_ilo_wage$ref_area_label)) #38

unique(fis_ilo_wage$currency)
# "Currency: Local currency" "Currency: 2017 PPP $"     "Currency: U.S. dollars" 

# Local currency -- needs to be PPP adjusted
fis_wage_local <- fis_ilo_wage %>% 
  filter(currency %in% "Currency: Local currency")

# Currency: U.S. dollars -- needs to be PPP adjusted
fis_wage_usd <- fis_ilo_wage %>% 
  filter(currency %in% "Currency: U.S. dollars")

# 2017 PPP $
fis_wage_2021ppp <- fis_ilo_wage %>% 
  filter(currency %in% "Currency: 2021 PPP $")

# run ohicore name_2_rgn 
fis_wage_ppp_cleaned <- name_2_rgn(df_in = fis_wage_2021ppp, 
                       fld_name = 'ref_area_label',
                       flds_unique = c("year"))

############# Bring in OECD data to adjust monthly earnings to 2021 PPP
```

Gapfill wage data

```{r}
# join with OHI regions
wage_region_join <- left_join(rgns_eez, fis_wage_ppp_cleaned, by = c("rgn_name", "rgn_id")) %>%
  select(-c(territory, admin_rgn_id, admin_country_name, 
            Notes, eez_iso3)) #country, classif2_label

data_year <- max(wage_region_join$year, na.rm = TRUE)

# ---- Within country gapfilling ----
wage_gf <- wage_region_join %>% 
   group_by(rgn_id, rgn_name) %>% 
  complete(year = 2008:data_year) %>% # ensures that there is a row for every year for each region, to ensure there are no gaps
  ungroup() %>%
  # First, create gapfilled boolean and method columns
  mutate(wg_gapfilled = ifelse(is.na(obs_value), "1", NA_character_),
         wg_gf_method = ifelse(is.na(obs_value), "1", NA_character_)) %>%
  # Regroup for gapfilling
  group_by(rgn_id, rgn_name) %>% 
  arrange(rgn_id, year) %>%   
  # Linear interpolation
  mutate(obs_value = na.approx(obs_value, 
                                        x = year, na.rm = FALSE)) %>% 
  mutate(wg_gapfilled = ifelse(wg_gapfilled == "1" & !is.na(obs_value), 
                               "gapfilled", wg_gapfilled),
         wg_gf_method = ifelse(wg_gf_method == "1" & !is.na(obs_value), 
                               "Interpolation", wg_gf_method)) %>% 
  # Upfilling and Downfiling
  tidyr::fill(obs_value, .direction = "updown") %>% 
  mutate(wg_gapfilled = ifelse(wg_gapfilled == "1" & !is.na(obs_value), 
                               "gapfilled", wg_gapfilled),
         wg_gf_method = ifelse(wg_gf_method == "1" & !is.na(obs_value), 
                               "Up/Downfilling", wg_gf_method))

table(wage_gf$wg_gf_method)
          # Interpolation Up/Downfilling 
          #          22            246 

length(unique(wage_gf$rgn_id)) # 221
colSums(is.na(wage_gf)) # 2688
nrow(wage_gf) # 3065
# ~ 88% NA currently. Will gapfill with georegion next
# Keep in mind this is including ALL OHI regions, that's why NA count is so high

```

```{r}
# ---- Georegion gapfilling ----

# Gapfill with regional means for wage data
rgns_eez_small <- rgns_eez %>%
  select(rgn_id, rgn_name)

georegions <- ohicore::georegions %>% 
  left_join(rgns_eez_small, by = "rgn_id")

# Find avg wage by georegion
wage_georgn <- wage_gf %>% 
  left_join(georegions, by = c("rgn_id", "rgn_name")) %>%
  # Get average for georgn and year
  group_by(r2, year) %>%
  mutate(mean_wage_r2 = mean(obs_value, na.rm = TRUE),
         # to make NaN = NAs
         mean_wage_r2 = ifelse(is.nan(mean_wage_r2), NA, mean_wage_r2)) %>%
  ungroup() %>%
  group_by(r1, year) %>%
  mutate(mean_wage_r1 = mean(obs_value, na.rm = TRUE),
         mean_wage_r1 = ifelse(is.nan(mean_wage_r1), NA, mean_wage_r1)) %>%
  ungroup()

# ---- Georegion gapfilling ----
wage_georgn_gf <- wage_georgn %>% 
  mutate(
    # Gapfilling record
    georgn_gapfill = case_when(
    is.na(obs_value) & !is.na(mean_wage_r2) ~ "r2",
    is.na(obs_value) & is.na(mean_wage_r2) & !is.na(mean_wage_r1) ~ "r1",
    .default = NA
  ),
  # Actual gapfilling
    obs_value = case_when(
    is.na(obs_value) & !is.na(mean_wage_r2) ~ mean_wage_r2,
    is.na(obs_value) & is.na(mean_wage_r2) & !is.na(mean_wage_r1) ~ mean_wage_r1,
    TRUE ~ obs_value)
  ) %>% 
  drop_na(year)

table(wage_georgn_gf$georgn_gapfill)
 #  r1   r2 
 # 936 1417 

# Regions with no wage data after all gapfilling
wage_georgn_gf %>% 
  filter(is.na(obs_value)) %>% 
  distinct(rgn_id, rgn_name) 

# Narrow wage columns before joining
wage_final <- wage_georgn_gf %>% 
  drop_na(obs_value) %>% 
  mutate(unit = "Currency: 2021 PPP $",
         sector = "tour",
         source = "ILOSTAT",
         annual_income = obs_value * 12) %>% 
  select(rgn_id, rgn_name, year, annual_income, unit, sector, source)

colSums(is.na(wage_final))
length(unique(wage_final$rgn_id)) # 210 final regions
# view(wage_final)

wage_export <- wage_final %>% 
  select(rgn_id, year, quality = annual_income)

write_csv(wage_export, here(int_dir, "liv_fis_quality.csv"))
```
