---
title: "NP Methods tables"
author: "Gage Clawson"
date: "8/18/2020"
output: html_document
---

This only needs to be done for the 2020 assessment year. 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

Here we need to create prep a list of natural product commodities that we are currently using given the new updates. 

```{r}
##prep the fishoil data
fishoil <- read_csv("globalprep/np/v2020/raw/msleckman.61.1-CatchMSY_Nis_FAOAreas.csv.csv") %>%
  dplyr::select("commodity" = "Species") %>%
  unique() %>%
  mutate(product = "fish_oil")

## now read in old commodities2products.csv 
coms <- read_csv("../v2019/raw/commodities2products.csv")

##filter out old fishoil products, sponges, seaweeds, corals, and shells
coms_filt <- coms %>%
  filter(product == "ornamentals")

## now read in seaweed species that we use: 
sw_spp <- read_csv("globalprep/np/v2020/raw/species_list_np_seaweeds_edited.csv") %>%
  dplyr::select("commodity" = "FAO_name") %>%
  unique() %>%
  mutate(product = "seaweeds")


## now rbind all three datasets to get our new commodities2produts.csv
coms2prod <- rbind(coms_filt, fishoil, sw_spp)

write.csv(coms2prod, "globalprep/np/v2020/raw/commodities2products_new.csv", row.names = FALSE)
```

```{r}
## prep commodities weighting table for 3 natural products
coms_weighting <- coms %>%
  dplyr::filter(product %in% c("seaweeds", "fish_oil", "ornamentals"))

write.csv(coms_weighting, "raw/commodities2products_weighting.csv")
```


