### Download population data
### version 4.1

NOTE: The following provides the links, but I could never directly download the data due to password issues and redirections, etc. Ultimately downloaded by hand and moved to directory.  

Center for International Earth Science Information Network - CIESIN - Columbia University. 2017. Gridded Population of the World, Version 4 (GPWv4): Population Density, Revision 10. Palisades, NY: NASA Socioeconomic Data and Applications Center (SEDAC). https://doi.org/10.7927/H4DZ068D. Accessed 25 Jan 2019.

```{r}

library(downloader)
library(here)
library(RCurl)
source('http://ohi-science.org/ohiprep_v2020/workflow/R/common.R')

url <- "http://sedac.ciesin.columbia.edu/downloads/data/gpw-v4/gpw-v4-population-density-rev10/gpw-v4-population-density-rev10_2000_30_sec_tif.zip"


td = tempdir()
# create the placeholder file
tf = tempfile(tmpdir=td, fileext=".zip")
# download into the placeholder file
download.file(url, tf)
unzip(tf)

ctnt = getURLContent(url) 

capabilities("libcurl")

```

# **2025 Updates**

[Posted June 17, 2025](https://www.earthdata.nasa.gov/news/data-from-sedac-available-again-earthdata-search):

On April 30, 2025, the contract for NASA's Socioeconomic Data and Applications Center (SEDAC), managed by Columbia University's Center for Integrated Earth System Information (CIESIN), was terminated and the datasets SEDAC curated were no longer available. Since then, the Earth Science Data and Information System (ESDIS) project has been working to get the datasets rehoused. Starting today, all SEDAC datasets have been relocated to Earthdata Cloud and can be found in Earthdata Search.

Access over 350 data collections previously available through SEDAC.

An Earthdata Login is required to view and download the data. If you are unfamiliar with the Earthdata Login and how to obtain an account, watch this tutorial video on what Earthdata Login is and how to get access.

All of the datasets are complete and will no longer be updated with new versions or collections. The Dataset Lifecycle Data Basics page explains collection progress states for more information.

## New Steps:

- Searched [SEDAC](https://search.earthdata.nasa.gov/search/granules?p=C3540929692-ESDIS&pg[0][v]=f&pg[0][gsk]=-start_date&q=GPWv4&tl=1277985600!5!!) for GPWv4

- Selected: Gridded Population of the World, Version 4 (GPWv4): Population Density Adjusted to Match 2015 Revision UN WPP Country Totals, Revision 11 and downloaded all the 30_sec_tif.zip files

- Selected: Gridded Population of the World, Version 4 (GPWv4): Population Count Adjusted to Match 2015 Revision of UN WPP Country Totals, Revision 11 and downloaded all the 30_sec_tif.zip files

- Created account to do so.

- Manually added it to home/shares/ohi/git-annex/globalprep/_raw_data/CIESEandCIAT_population/d2025

