---
title: "World Bank Service Earnings Data Prep"

---


```{r}
rm(list=ls())
library(tidyverse)
library(readr)
library(readxl)
library(here)
library(janitor)
library(readxl)
library(zoo)
library(tidyr)
library(dplyr)
library(reshape2)
```


```{r}
current_year <- 2024
assess_year <- paste0("v", current_year)

## Workflow/R/common.R loaded to obtain dir_M 
source(here("workflow/R/common.R"))

fp_join <- file.path(dir_M, "git-annex/globalprep/_raw_data/UNWTO/d2024/join_database_w_definitions.xlsx")
fp_ppp <- file.path(dir_M, "git-annex/globalprep/_raw_data/UNWTO/d2024/SNA_TABLE4_27062024190625956.csv")

wages <- read_excel(fp_join, 
                   skip = 3, col_names = TRUE) %>% 
  janitor::clean_names()

wages_2018 = wages %>% 
  filter(year_of_survey >= 2012)

# column_names <- as.list(colnames(wages_2018))

wages_filtered <- wages_2018 %>%  
  dplyr::select(1:10, total_population, labor_force_aged_15_64, 25, 61, 66, 72:74, 75, 79, 81, 83) %>% 
  filter(subsample == "All") %>% 
  mutate(country_name = as.factor(country_name)) %>% 
  arrange(desc(real_median_hourly_wages_in_usd_base_2011_ppp_adjusted)) %>% 
    filter(!is.na(median_earnings_for_wage_workers_per_month_in_service_local_nominal_currency)) %>% 
  rename(median_service_wage_local = median_earnings_for_wage_workers_per_month_in_service_local_nominal_currency )

ggplot(wages_filtered, aes(y = reorder(country_name, median_service_wage_local), x = median_service_wage_local)) +
  geom_boxplot() + 
  theme(axis.text.y = element_text(size = 10))

## We want to convert the median monthly wages median_service_wage_local for each country for each year 
wages_subset <- wages_filtered %>% 
  dplyr::select(1:3, 7, total_population, labor_force_aged_15_64, median_service_wage_local) %>% 
  mutate(yearly_local_wage = median_service_wage_local*12) %>% 
  rename(date = year_of_survey) %>% 
  mutate(date = as.character(date))

# ----------- Join with OHI Regions -----------

# read in OHI regions for joining
region_names <- read_csv("https://raw.githubusercontent.com/OHI-Science/ohi-global/draft/eez/spatial/regions_list.csv") %>% 
  janitor::clean_names()

# prep column names for joining
wages_clean <- wages_subset %>% 
  rename(eez_iso3 = country_code,
         admin_country_name = country_name)


# join by country_code and eez_iso3
wages_merge <- inner_join(x = wages_clean, region_names, by = c("eez_iso3", "admin_country_name"))

wages_merge <- wages_merge %>% 
  dplyr::relocate(rgn_id, .before = admin_country_name) %>% 
  select(-notes)

# ------------- Bring in in PPP data conversion factors ----------------
# ppp_conversion <- read_csv(fp_ppp) %>% 
#   janitor::clean_names()
# 
# ppp_prc = ppp_conversion %>% 
#   filter(transact == "PPPGDP") %>% 
#   filter(time >= 2012) %>% 
#   rename(date = year) %>% 
#   mutate(date = as.character(date))
# 
# ppp_clean <- ppp_prc %>% 
#   dplyr::select(c(location, country, transact, date, unit, value)) %>% 
#   rename(eez_iso3 = location,
#          admin_country_name = country)
# 
# ppp_merge <- inner_join(x = ppp_clean, region_names, by = c("eez_iso3", "admin_country_name"))
# 
# ppp_merge <- ppp_merge %>% 
#   dplyr::relocate(rgn_id, .before = eez_iso3)
# 
# wages_ppp <- inner_join(x = wages_merge, ppp_merge, by = c("rgn_id", "date"))
# 
# wages_ppp_converted <- wages_ppp %>% 
#   mutate(yearly_wages_ppp_adjusted_by_year = yearly_local_wage/value) %>% 
#   mutate(rgn_id = as.character(rgn_id))
# 
# ggplot(wages_ppp_converted, aes(y = yearly_wages_ppp_adjusted_by_year, x = as.numeric(date), color = rgn_id)) + 
#   geom_line()
```

```{r}
fp_unwto <- file.path(dir_M, "/git-annex/globalprep/_raw_data/UNWTO/d2024/unwto-all-data-download_0.xlsx")

unwto <- read_excel(fp_unwto, col_names = TRUE, sheet = "Employment", skip = 2, na = c("..")) %>% 
  janitor::clean_names()

unwto_subset <- unwto %>% 
  dplyr::select(-c(c,s,c_s, x5, x7, x8, x38)) %>% 
  fill(basic_data_and_indicators, .direction = "down") %>% 
  filter(x6 == "Total")

unwto_long <- unwto_subset %>% 
  pivot_longer(cols = c(5:31), names_to = "year", values_to = "thousand_employees") %>% 
  mutate(year = str_remove_all(year, "x")) %>% 
  rename(country = basic_data_and_indicators) %>% 
  mutate(country = str_to_title(country))

# using countrycode::countrycode

# install.packages("countrycode")
library(countrycode)


country_regex_to_iso3c <- function(country_string) {
  country_string %>%
    countrycode::countrycode(origin = "country.name", destination = "iso3c", origin_regex = TRUE)
}

# adding iso3 codes
unwto_clean_codes <- unwto_long %>% 
  mutate(iso3c = country_regex_to_iso3c(country))



ggplot(unwto_clean_codes, aes(x = as.numeric(year), y = thousand_employees, color = country)) + 
  geom_line() + 
  # ylim(0,10000) +
  theme(legend.position = "none")

jobs_rgn_join <- left_join(region_names, unwto_clean_codes, by = c("eez_iso3" = "iso3c"))

jobs_rgn_nona <- jobs_rgn_join %>% 
  filter(!is.na(thousand_employees))

jobs_rgn_2012 <- jobs_rgn_nona %>% 
  mutate(year = as.numeric(year)) %>% 
  filter(year >= 2012) %>% 
  mutate(year = as.character(year),
         rgn_id = as.character(rgn_id))

# pop_ppp_converted <- wages_ppp_converted %>% 
#   rename(year = date) %>%
#   mutate(year = as.character(year),
#          rgn_id = as.character(rgn_id)) %>% 
#   select(rgn_id, admin_country_name.x, total_population, labor_force_aged_15_64, year, unit, yearly_wages_ppp_adjusted_by_year) %>% 
#   rename(admin_country_name = admin_country_name.x)

# jobs_rgn_2012$rgn

# jobs_wages_join <- left_join(jobs_rgn_2012, pop_ppp_converted, by = c("rgn_id", "year"))

jobs_wages_proportional_employment <- jobs_wages_join %>% 
  mutate(total_tourism_employees = thousand_employees*1000) %>% 
  dplyr::relocate(total_tourism_employees, .before = total_population) %>% 
  mutate(proportional_tourism_employment_total_pop = total_tourism_employees/total_population,
         proportional_tourism_employment_labor_force = total_tourism_employees/labor_force_aged_15_64) %>% 
  select(-c(notes.x, notes.y))
  
proportional_employement_nona <- jobs_wages_proportional_employment %>% 
  na.omit() %>% 
  mutate(year = as.numeric(year))

ggplot(proportional_employement_nona, aes(x = year, y = proportional_tourism_employment_labor_force, color = rgn_id)) + 
  geom_line()

library(plotly)
line_plot <- plot_ly(proportional_employement_nona, x = ~year, y = ~proportional_tourism_employment_labor_force, color = ~admin_country_name.x, type = "scatter", mode = "lines") %>%
  layout(title = "All Regions: Proportional Employment Line Chart", 
         xaxis = list(title = "Year"),
         yaxis = list(title = "Number of people employed by the tourism sector"))

line_plot

# htmlwidgets::saveWidget(line_plot, file = "proportional_jobs.html")


penona_pivot <- proportional_employement_nona %>% 
  pivot_longer(cols = c(proportional_tourism_employment_labor_force, yearly_wages_ppp_adjusted_by_year), names_to = "metric", values_to = "value") 
# %>% 
  # filter(admin_country_name.x %in% c("Indonesia", "Brazil", "Cyprus", "Argentina", "India"))

ggplot(penona_pivot, aes(x = as.numeric(year), y = value, color = admin_country_name.x)) +
  geom_line() + 
  facet_wrap(~metric, scales = "free", ncol = 1)
length(unique(penona_pivot$admin_country_name.x))
length(unique(wages_ppp_converted$rgn_id))
```

```{r}
## 
fp.newwage <- file.path(dir_M,
                        "git-annex/globalprep/_raw_data/ILOSTAT/d2024/EAR_4MTH_SEX_ECO_CUR_NB_A-filtered-2024-06-28.csv")

new_wage_data <- read_csv(fp.newwage)

new_wage_data2 <- new_wage_data %>% 
  filter(source.label == "HIES - Household Budget Survey")

new_wage_data_ppp <- new_wage_data %>% 
  rename(monthly_wage = obs_value) %>% 
  filter(classif2.label == "Currency: 2017 PPP $") %>% 
  group_by(ref_area.label) 

country <- as.data.frame(unique(new_wage_data_ppp$ref_area.label))

countries = sample_n(country, size = 15)

test <- new_wage_data_ppp[new_wage_data_ppp$ref_area.label %in% countries[, 1], ]

range(new_wage_data$time) ## 2014-2024 
length(unique(new_wage_data$ref_area.label)) ## 150 countries

ggplot(test, aes(x = time, y = monthly_wage, color = ref_area.label)) + 
  geom_point() + 
  geom_smooth(method = "lm") +
  ylim(0, 10000)

# years <- tibble(iso3 = rep(as.character(region_names$eez_iso3), 6)) %>% 
#   group_by(iso3) %>% 
#   mutate(year = rep(2014:2019))

```


```{r}
# preliminary cleanings
wage_data_clean <- new_wage_data %>% 
  # lower_snake_case
  janitor::clean_names() %>% 
  # more intuitive value name
  rename(monthly_wage = obs_value) %>% 
  # filter to PPP adjusted data (this accounts for inflation, diff in currencies globally, cost of living etc.)
  filter(classif2_label == "Currency: 2017 PPP $") %>% 
  # group by country/region
  group_by(ref_area_label) %>% 
  # set column name to year
  rename(year = time) %>% 
  # filter to the cap date range from the jobs data -- 2019
  filter(year %in% c(2014:2019)) %>%  
  # add iso3 column, tourism sector label
  mutate(iso3 = country_regex_to_iso3c(ref_area_label),
         sector = "tour") %>% 
  select(c(ref_area_label, iso3, year, monthly_wage, classif2_label))
  


# make sequence of years for gapfilling ----
# note: data does not have wage data for some years in some countries -- we want to account for that by leaving them as NAs, then gapfilling with the average between the pre and post years

years_df <- tibble(iso3 = wage_data_clean$iso3) %>% 
  group_by(iso3) %>% 
  summarize(year = seq(2014, 2019))


wage_data_years <- left_join(years_df, wage_data_clean, by = c("iso3", "year"))

# filling in country names when possible --- 
wage_years_filled <- wage_data_years %>% 
  group_by(iso3) %>% 
  fill(ref_area_label, .direction = "downup") %>% 
  ungroup()

# =================

# test gapfilling
gap_fill_test <- wage_years_filled %>% 
  mutate(ref_area_label = as.factor(ref_area_label)) %>% 
  mutate(lm_est = list(lm(monthly_wage ~ year + ref_area_label)))


lm_test <- lm(monthly_wage ~ year + ref_area_label, data = wage_years_filled)
summary(lm_test)

lm_test$coefficients 

# wage_years_filled$lm_values <- lm_test$fitted.values

# gap filling  ----
wage_gf <- wage_years_filled %>% 
  group_by(ref_area_label) %>% 
  # interpolate (fill missing values between 2 values)
  mutate(appx_wage = zoo::na.approx(monthly_wage, # using values in this column
                                    na.rm = FALSE, # don't replace (internal) NAs in new column that can't be approximated
                                    #  extrapolate using rule = 2 from approx(), uses closest data extreme to extrapolate for leading and trailing NAs
                                    rule = 2))
  
# note: need more than 1 data point to do any approximation. 
# also, extremes (leading and trailing) are just copied data points from nearest extreme
```

```{r}
fp.lbr_frc <- file.path(dir_M, "git-annex/globalprep/_raw_data/WorldBank/d2024/worldbank_labor_force_raw.xls")

lbr_frc <- read_excel(fp.lbr_frc, skip = 3, na = "") %>% 
  janitor::clean_names()

lbr_long <- lbr_frc %>% 
  pivot_longer(cols = c(5:68), names_to = "year", values_to = "labor_force") %>% 
  mutate(year = str_remove_all(year, pattern = "x"),
         year = as.numeric(year))

lbr_rgn <- left_join(lbr_long, region_names, by =c("country_code" = "eez_iso3"))

lbr_rgn_nona <- lbr_rgn %>% 
  filter(!is.na(admin_rgn_id)) %>% 
  filter(year >= 1991)
```

